"""garden eject — generate SDK scaffold from an agent.yaml file.

Converts a Low Code YAML definition into a Full Code Python SDK file,
enabling tier mobility from YAML to programmatic control.

Usage:
    garden eject agent.yaml --sdk python
    garden eject agent.yaml --sdk python --output agents/my-agent/agent_sdk.py
"""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

console = Console()


def _generate_python_sdk(yaml_content: str) -> str:
    """Generate Python SDK code that recreates the agent from YAML."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise typer.BadParameter("Invalid YAML: expected a mapping at the top level")

    lines: list[str] = [
        '"""Agent definition generated by `garden eject`.',
        "",
        "Edit this file to add custom routing, middleware, hooks, and state logic.",
        "Then deploy with: python agent_sdk.py",
        '"""',
        "",
        "from agenthub import Agent, Tool, Model, Memory",
        "",
    ]

    # Start builder chain
    name = data.get("name", "my-agent")
    version = data.get("version", "1.0.0")
    team = data.get("team", "default")
    desc = data.get("description", "")

    chain_parts: list[str] = []

    init_args = f'"{name}", version="{version}", team="{team}"'
    if desc:
        init_args += f', description="{desc}"'
    owner = data.get("owner", "")
    if owner:
        init_args += f', owner="{owner}"'
    framework = data.get("framework", "custom")
    if framework != "custom":
        init_args += f', framework="{framework}"'

    chain_parts.append(f"    Agent({init_args})")

    # Model
    model = data.get("model")
    if isinstance(model, dict):
        primary = model.get("primary", "")
        fallback = model.get("fallback")
        model_args = f'primary="{primary}"'
        if fallback:
            model_args += f', fallback="{fallback}"'
        temp = model.get("temperature")
        if temp is not None and temp != 0.7:
            model_args += f", temperature={temp}"
        max_tok = model.get("max_tokens")
        if max_tok is not None and max_tok != 4096:
            model_args += f", max_tokens={max_tok}"
        chain_parts.append(f"    .with_model({model_args})")

    # Prompts
    prompts = data.get("prompts")
    if isinstance(prompts, dict) and "system" in prompts:
        system = prompts["system"]
        chain_parts.append(f'    .with_prompt(system="{system}")')

    # Tools
    tools = data.get("tools", [])
    for tool in tools:
        if isinstance(tool, dict):
            if "ref" in tool:
                chain_parts.append(f'    .with_tool(Tool.from_ref("{tool["ref"]}"))')
            elif "name" in tool:
                desc = tool.get("description", "")
                desc_part = f', description="{desc}"' if desc else ""
                chain_parts.append(f'    .with_tool(Tool(name="{tool["name"]}"{desc_part}))')

    # Memory
    memory = data.get("memory")
    if isinstance(memory, dict):
        backend = memory.get("backend", "in_memory")
        mem_args = f'backend="{backend}"'
        max_msg = memory.get("max_messages")
        if max_msg and max_msg != 100:
            mem_args += f", max_messages={max_msg}"
        chain_parts.append(f"    .with_memory({mem_args})")

    # Guardrails
    for g in data.get("guardrails", []):
        if isinstance(g, str):
            chain_parts.append(f'    .with_guardrail("{g}")')

    # Deploy
    deploy = data.get("deploy")
    if isinstance(deploy, dict):
        cloud = deploy.get("cloud", "local")
        deploy_args = f'cloud="{cloud}"'
        runtime = deploy.get("runtime")
        if runtime:
            deploy_args += f', runtime="{runtime}"'
        region = deploy.get("region")
        if region:
            deploy_args += f', region="{region}"'
        chain_parts.append(f"    .with_deploy({deploy_args})")

    # Tags
    tags = data.get("tags", [])
    if tags:
        tag_str = ", ".join(f'"{t}"' for t in tags)
        chain_parts.append(f"    .tag({tag_str})")

    # Assemble
    lines.append("agent = (")
    lines.append("\n".join(chain_parts))
    lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("# --- Customize below this line ---")
    lines.append("")
    lines.append("# Add middleware (runs on every turn)")
    lines.append("# @agent.use")
    lines.append("# def log_turns(message, context, next_fn):")
    lines.append('#     print(f"Turn: {message}")')
    lines.append("#     return next_fn(message, context)")
    lines.append("")
    lines.append("# Register event hooks")
    lines.append("# @agent.on('turn_start')")
    lines.append("# def on_start(context):")
    lines.append('#     print("Turn started")')
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    errors = agent.validate()")
    lines.append("    if errors:")
    lines.append('        print("Validation errors:", errors)')
    lines.append("    else:")
    lines.append('        print("Agent is valid!")')
    lines.append("        print(agent.to_yaml())")
    lines.append("")

    return "\n".join(lines)


def eject(
    config_path: Path = typer.Argument(
        ...,
        help="Path to agent.yaml",
        exists=True,
        readable=True,
    ),
    sdk: str = typer.Option(
        "python",
        "--sdk",
        help="Target SDK language (currently only 'python' is supported)",
    ),
    output: str | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output file path. Defaults to agents/<name>/agent_sdk.py",
    ),
) -> None:
    """Generate SDK scaffold code from an agent.yaml file.

    Converts a Low Code YAML definition to Full Code SDK for
    custom routing, middleware, hooks, and state management.
    """
    if sdk != "python":
        console.print(f"[red]Unsupported SDK: {sdk}. Only 'python' is supported.[/red]")
        raise typer.Exit(1)

    yaml_content = config_path.read_text(encoding="utf-8")

    try:
        code = _generate_python_sdk(yaml_content)
    except Exception as e:
        console.print(f"[red]Failed to generate SDK code: {e}[/red]")
        raise typer.Exit(1) from e

    # Determine output path
    if output:
        out_path = Path(output)
    else:
        import yaml

        data = yaml.safe_load(yaml_content)
        name = data.get("name", "agent") if isinstance(data, dict) else "agent"
        out_path = Path("agents") / name / "agent_sdk.py"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(code, encoding="utf-8")

    console.print(
        Panel(
            Syntax(code, "python", theme="monokai", line_numbers=True),
            title=f"[green]Ejected to {out_path}[/green]",
            border_style="green",
        )
    )
    console.print(f"\n[green]SDK scaffold written to[/green] [bold]{out_path}[/bold]")
    console.print("[dim]Edit the file to add custom routing, middleware, and hooks.[/dim]")
