"""agentbreeder eject — generate SDK scaffold from an agent.yaml file.

Converts a Low Code YAML definition into a Full Code Python SDK file,
enabling tier mobility from YAML to programmatic control.

Usage:
    agentbreeder eject agent.yaml --sdk python
    agentbreeder eject agent.yaml --sdk python --output agents/my-agent/agent_sdk.py
"""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_class_name(slug: str) -> str:
    """Convert a slug like 'my-agent' or 'customer_support' to 'MyAgent'."""
    import re

    parts = re.split(r"[-_]", slug)
    return "".join(part.capitalize() for part in parts if part)


# ---------------------------------------------------------------------------
# CrewAI scaffold
# ---------------------------------------------------------------------------


def _generate_crewai_scaffold(yaml_content: str, out_dir: Path) -> None:
    """Write a CrewAI project scaffold from agent YAML into *out_dir*."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise ValueError("Invalid YAML: expected a mapping at the top level")

    name: str = data.get("name", "my-agent")
    description: str = data.get("description") or "an AgentBreeder agent"
    class_name = _to_class_name(name)

    # crew.py
    crew_py = f'''"""CrewAI agent scaffold generated by AgentBreeder eject."""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task


@CrewBase
class {class_name}Crew:
    """Crew for {name}."""

    agents_config = "config/agents.yaml"
    tasks_config = "config/tasks.yaml"

    @agent
    def primary_agent(self) -> Agent:
        return Agent(
            config=self.agents_config["primary_agent"],  # type: ignore[index]
            verbose=True,
        )

    @task
    def primary_task(self) -> Task:
        return Task(
            config=self.tasks_config["primary_task"],  # type: ignore[index]
        )

    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
'''

    # config/agents.yaml
    agents_yaml = f"""primary_agent:
  role: >
    {name} Primary Agent
  goal: >
    {description}
  backstory: >
    You are a specialized agent responsible for {description}.
"""

    # config/tasks.yaml
    tasks_yaml = f"""primary_task:
  description: >
    Execute the primary task for {name}.
  expected_output: >
    A complete, accurate response to the task.
  agent: primary_agent
"""

    # requirements.txt
    requirements = "crewai>=0.80.0\n"

    # Write files
    out_dir.mkdir(parents=True, exist_ok=True)
    config_dir = out_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "crew.py").write_text(crew_py, encoding="utf-8")
    (config_dir / "agents.yaml").write_text(agents_yaml, encoding="utf-8")
    (config_dir / "tasks.yaml").write_text(tasks_yaml, encoding="utf-8")
    (out_dir / "requirements.txt").write_text(requirements, encoding="utf-8")


# ---------------------------------------------------------------------------
# Google ADK scaffold
# ---------------------------------------------------------------------------


def _generate_google_adk_scaffold(yaml_content: str, out_dir: Path) -> None:
    """Write a Google ADK project scaffold from agent YAML into *out_dir*."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise ValueError("Invalid YAML: expected a mapping at the top level")

    name: str = data.get("name", "my-agent")
    description: str = data.get("description") or "A helpful agent"
    model_cfg = data.get("model") or {}
    model: str = model_cfg.get("primary", "gemini-2.0-flash") if isinstance(model_cfg, dict) else "gemini-2.0-flash"
    has_subagents = bool(data.get("subagents"))

    if has_subagents:
        agent_py = f'''"""Google ADK agent scaffold generated by AgentBreeder eject."""

import os

from google.adk.agents import LlmAgent, SequentialAgent

_sub1 = LlmAgent(
    name="{name}_step1",
    model="{model}",
    description="First step of {name}",
    instruction="Complete the first step of the task.",
)

_sub2 = LlmAgent(
    name="{name}_step2",
    model="{model}",
    description="Second step of {name}",
    instruction="Complete the second step of the task.",
)

root_agent = SequentialAgent(
    name="{name}",
    description="{description}",
    sub_agents=[_sub1, _sub2],
)
'''
    else:
        agent_py = f'''"""Google ADK agent scaffold generated by AgentBreeder eject."""

import os

from google.adk.agents import LlmAgent

root_agent = LlmAgent(
    name="{name}",
    model="{model}",
    description="{description}",
    instruction=(
        "You are a helpful agent. Complete the user\'s request accurately and concisely."
    ),
)
'''

    requirements = "google-adk>=1.29.0\n"

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "agent.py").write_text(agent_py, encoding="utf-8")
    (out_dir / "requirements.txt").write_text(requirements, encoding="utf-8")


# ---------------------------------------------------------------------------
# Claude SDK scaffold
# ---------------------------------------------------------------------------


def _generate_claude_sdk_scaffold(yaml_content: str, out_dir: Path) -> None:
    """Write a Claude SDK project scaffold from agent YAML into *out_dir*."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise ValueError("Invalid YAML: expected a mapping at the top level")

    model_cfg = data.get("model") or {}
    model: str = model_cfg.get("primary", "claude-sonnet-4-6") if isinstance(model_cfg, dict) else "claude-sonnet-4-6"

    prompts_cfg = data.get("prompts") or {}
    system_prompt: str = (
        prompts_cfg.get("system", "You are a helpful assistant.")
        if isinstance(prompts_cfg, dict)
        else "You are a helpful assistant."
    )
    if not system_prompt:
        system_prompt = "You are a helpful assistant."

    agent_py = f'''"""Claude SDK agent scaffold generated by AgentBreeder eject."""

from __future__ import annotations

import anthropic
from anthropic.types import ToolParam

client = anthropic.AsyncAnthropic()

MODEL = "{model}"
SYSTEM_PROMPT = "{system_prompt}"

TOOLS: list[ToolParam] = [
    # Add your tools here. Example:
    # {{
    #     "name": "search",
    #     "description": "Search for information",
    #     "input_schema": {{
    #         "type": "object",
    #         "properties": {{"query": {{"type": "string"}}}},
    #         "required": ["query"],
    #     }},
    # }},
]


async def run_agent(user_input: str) -> str:
    """Run the agent with a tool-use loop."""
    messages: list[dict] = [{{"role": "user", "content": user_input}}]

    while True:
        response = await client.messages.create(
            model=MODEL,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            tools=TOOLS,
            messages=messages,
        )

        if response.stop_reason == "end_turn":
            # Collect all text blocks
            return "".join(
                block.text for block in response.content if hasattr(block, "text")
            )

        if response.stop_reason == "tool_use":
            # Process tool calls
            messages.append({{"role": "assistant", "content": response.content}})
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    # TODO: dispatch to your actual tool implementations
                    result = f"Tool {{block.name}} called with {{block.input}}"
                    tool_results.append(
                        {{
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": result,
                        }}
                    )
            messages.append({{"role": "user", "content": tool_results}})
            continue

        # Unexpected stop reason
        break

    return ""
'''

    requirements = "anthropic>=0.50.0\n"

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "agent.py").write_text(agent_py, encoding="utf-8")
    (out_dir / "requirements.txt").write_text(requirements, encoding="utf-8")


def _generate_python_sdk(yaml_content: str) -> str:
    """Generate Python SDK code that recreates the agent from YAML."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise typer.BadParameter("Invalid YAML: expected a mapping at the top level")

    lines: list[str] = [
        '"""Agent definition generated by `agentbreeder eject`.',
        "",
        "Edit this file to add custom routing, middleware, hooks, and state logic.",
        "Then deploy with: python agent_sdk.py",
        '"""',
        "",
        "from agenthub import Agent, Tool, Model, Memory",
        "",
    ]

    # Start builder chain
    name = data.get("name", "my-agent")
    version = data.get("version", "1.0.0")
    team = data.get("team", "default")
    desc = data.get("description", "")

    chain_parts: list[str] = []

    init_args = f'"{name}", version="{version}", team="{team}"'
    if desc:
        init_args += f', description="{desc}"'
    owner = data.get("owner", "")
    if owner:
        init_args += f', owner="{owner}"'
    framework = data.get("framework", "custom")
    if framework != "custom":
        init_args += f', framework="{framework}"'

    chain_parts.append(f"    Agent({init_args})")

    # Model
    model = data.get("model")
    if isinstance(model, dict):
        primary = model.get("primary", "")
        fallback = model.get("fallback")
        model_args = f'primary="{primary}"'
        if fallback:
            model_args += f', fallback="{fallback}"'
        temp = model.get("temperature")
        if temp is not None and temp != 0.7:
            model_args += f", temperature={temp}"
        max_tok = model.get("max_tokens")
        if max_tok is not None and max_tok != 4096:
            model_args += f", max_tokens={max_tok}"
        chain_parts.append(f"    .with_model({model_args})")

    # Prompts
    prompts = data.get("prompts")
    if isinstance(prompts, dict) and "system" in prompts:
        system = prompts["system"]
        chain_parts.append(f'    .with_prompt(system="{system}")')

    # Tools
    tools = data.get("tools", [])
    for tool in tools:
        if isinstance(tool, dict):
            if "ref" in tool:
                chain_parts.append(f'    .with_tool(Tool.from_ref("{tool["ref"]}"))')
            elif "name" in tool:
                desc = tool.get("description", "")
                desc_part = f', description="{desc}"' if desc else ""
                chain_parts.append(f'    .with_tool(Tool(name="{tool["name"]}"{desc_part}))')

    # Memory
    memory = data.get("memory")
    if isinstance(memory, dict):
        backend = memory.get("backend", "in_memory")
        mem_args = f'backend="{backend}"'
        max_msg = memory.get("max_messages")
        if max_msg and max_msg != 100:
            mem_args += f", max_messages={max_msg}"
        chain_parts.append(f"    .with_memory({mem_args})")

    # Guardrails
    for g in data.get("guardrails", []):
        if isinstance(g, str):
            chain_parts.append(f'    .with_guardrail("{g}")')

    # Deploy
    deploy = data.get("deploy")
    if isinstance(deploy, dict):
        cloud = deploy.get("cloud", "local")
        deploy_args = f'cloud="{cloud}"'
        runtime = deploy.get("runtime")
        if runtime:
            deploy_args += f', runtime="{runtime}"'
        region = deploy.get("region")
        if region:
            deploy_args += f', region="{region}"'
        chain_parts.append(f"    .with_deploy({deploy_args})")

    # Tags
    tags = data.get("tags", [])
    if tags:
        tag_str = ", ".join(f'"{t}"' for t in tags)
        chain_parts.append(f"    .tag({tag_str})")

    # Assemble
    lines.append("agent = (")
    lines.append("\n".join(chain_parts))
    lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("# --- Customize below this line ---")
    lines.append("")
    lines.append("# Add middleware (runs on every turn)")
    lines.append("# @agent.use")
    lines.append("# def log_turns(message, context, next_fn):")
    lines.append('#     print(f"Turn: {message}")')
    lines.append("#     return next_fn(message, context)")
    lines.append("")
    lines.append("# Register event hooks")
    lines.append("# @agent.on('turn_start')")
    lines.append("# def on_start(context):")
    lines.append('#     print("Turn started")')
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    errors = agent.validate()")
    lines.append("    if errors:")
    lines.append('        print("Validation errors:", errors)')
    lines.append("    else:")
    lines.append('        print("Agent is valid!")')
    lines.append("        print(agent.to_yaml())")
    lines.append("")

    return "\n".join(lines)


def _generate_typescript_sdk(yaml_content: str) -> str:
    """Generate TypeScript SDK code that recreates the agent from YAML."""
    import yaml

    data = yaml.safe_load(yaml_content)
    if not isinstance(data, dict):
        raise typer.BadParameter("Invalid YAML: expected a mapping at the top level")

    lines: list[str] = [
        "/** Agent definition generated by `agentbreeder eject --sdk typescript`.",
        " *",
        " * Edit this file to add custom logic, then deploy with: npx ts-node agent.ts",
        " */",
        "",
        'import { Agent, Tool } from "@agentbreeder/sdk";',
        "",
    ]

    name = data.get("name", "my-agent")
    version = data.get("version", "1.0.0")
    team = data.get("team", "default")
    desc = data.get("description", "")
    owner = data.get("owner", "")
    framework = data.get("framework", "custom")

    opts_parts: list[str] = [f'  version: "{version}"']
    opts_parts.append(f'  team: "{team}"')
    if desc:
        opts_parts.append(f'  description: "{desc}"')
    if owner:
        opts_parts.append(f'  owner: "{owner}"')
    if framework != "custom":
        opts_parts.append(f'  framework: "{framework}"')

    lines.append(f'const agent = new Agent("{name}", {{')
    lines.append(",\n".join(opts_parts))
    lines.append("})")

    # Model
    model = data.get("model")
    if isinstance(model, dict):
        primary = model.get("primary", "")
        fallback = model.get("fallback")
        opts = []
        if fallback:
            opts.append(f'fallback: "{fallback}"')
        temp = model.get("temperature")
        if temp is not None and temp != 0.7:
            opts.append(f"temperature: {temp}")
        opts_str = ", { " + ", ".join(opts) + " }" if opts else ""
        lines.append(f'  .withModel("{primary}"{opts_str})')

    # Prompts
    prompts = data.get("prompts")
    if isinstance(prompts, dict) and "system" in prompts:
        lines.append(f'  .withPrompt("{prompts["system"]}")')

    # Tools
    for tool in data.get("tools", []):
        if isinstance(tool, dict):
            if "ref" in tool:
                lines.append(f'  .withTool(Tool.fromRef("{tool["ref"]}"))')
            elif "name" in tool:
                lines.append(f'  .withTool(new Tool({{ name: "{tool["name"]}" }}))')

    # Subagents
    for sub in data.get("subagents", []):
        if isinstance(sub, dict) and "ref" in sub:
            sub_desc = sub.get("description", "")
            desc_part = f', {{ description: "{sub_desc}" }}' if sub_desc else ""
            lines.append(f'  .withSubagent("{sub["ref"]}"{desc_part})')

    # Guardrails
    for g in data.get("guardrails", []):
        if isinstance(g, str):
            lines.append(f'  .withGuardrail("{g}")')

    # Deploy
    deploy = data.get("deploy")
    if isinstance(deploy, dict):
        cloud = deploy.get("cloud", "local")
        lines.append(f'  .withDeploy("{cloud}")')

    # Tags
    tags = data.get("tags", [])
    if tags:
        tag_str = ", ".join(f'"{t}"' for t in tags)
        lines.append(f"  .tag({tag_str})")

    lines.append(";")
    lines.append("")
    lines.append("// Validate and output YAML")
    lines.append("const errors = agent.validate();")
    lines.append("if (errors.length > 0) {")
    lines.append('  console.error("Validation errors:", errors);')
    lines.append("} else {")
    lines.append('  console.log("Agent is valid!");')
    lines.append("  console.log(agent.toYaml());")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def eject(
    config_path: Path = typer.Argument(
        ...,
        help="Path to agent.yaml",
        exists=True,
        readable=True,
    ),
    sdk: str = typer.Option(
        "python",
        "--sdk",
        help="Target SDK language: 'python' or 'typescript'",
    ),
    output: str | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output file path. Defaults to agents/<name>/agent_sdk.{py,ts}",
    ),
) -> None:
    """Generate SDK scaffold code from an agent.yaml file.

    Converts a Low Code YAML definition to Full Code SDK for
    custom routing, middleware, hooks, and state management.
    """
    import yaml

    yaml_content = config_path.read_text(encoding="utf-8")

    # Detect framework from YAML to dispatch to the right scaffold generator
    try:
        _parsed = yaml.safe_load(yaml_content)
        framework = _parsed.get("framework", "") if isinstance(_parsed, dict) else ""
    except Exception:
        framework = ""

    # Determine output directory for framework scaffolds
    if output:
        out_dir = Path(output)
    else:
        data_for_name = _parsed if isinstance(_parsed, dict) else {}
        agent_name = data_for_name.get("name", "agent")
        out_dir = Path("agents") / agent_name

    if framework == "crewai":
        try:
            _generate_crewai_scaffold(yaml_content, out_dir)
        except Exception as e:
            console.print(f"[red]Failed to generate CrewAI scaffold: {e}[/red]")
            raise typer.Exit(1) from e
        typer.echo(f"CrewAI scaffold written to {out_dir}")
        typer.echo("  crew.py          — CrewAI crew definition")
        typer.echo("  config/agents.yaml  — Agent configs")
        typer.echo("  config/tasks.yaml   — Task configs")
        typer.echo("  requirements.txt — Python dependencies")
        return

    elif framework == "google_adk":
        try:
            _generate_google_adk_scaffold(yaml_content, out_dir)
        except Exception as e:
            console.print(f"[red]Failed to generate Google ADK scaffold: {e}[/red]")
            raise typer.Exit(1) from e
        typer.echo(f"Google ADK scaffold written to {out_dir}")
        typer.echo("  agent.py         — ADK agent definition")
        typer.echo("  requirements.txt — Python dependencies")
        return

    elif framework == "claude_sdk":
        try:
            _generate_claude_sdk_scaffold(yaml_content, out_dir)
        except Exception as e:
            console.print(f"[red]Failed to generate Claude SDK scaffold: {e}[/red]")
            raise typer.Exit(1) from e
        typer.echo(f"Claude SDK scaffold written to {out_dir}")
        typer.echo("  agent.py         — Claude SDK async agent with tool loop")
        typer.echo("  requirements.txt — Python dependencies")
        return

    # Fall through to legacy python/typescript SDK generation
    if sdk not in ("python", "typescript"):
        console.print(f"[red]Unsupported SDK: {sdk}. Use 'python' or 'typescript'.[/red]")
        raise typer.Exit(1)

    try:
        if sdk == "python":
            code = _generate_python_sdk(yaml_content)
            lang = "python"
            ext = "py"
        else:
            code = _generate_typescript_sdk(yaml_content)
            lang = "typescript"
            ext = "ts"
    except Exception as e:
        console.print(f"[red]Failed to generate SDK code: {e}[/red]")
        raise typer.Exit(1) from e

    # Determine output path
    if output:
        out_path = Path(output)
    else:
        data = yaml.safe_load(yaml_content)
        name = data.get("name", "agent") if isinstance(data, dict) else "agent"
        out_path = Path("agents") / name / f"agent_sdk.{ext}"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(code, encoding="utf-8")

    console.print(
        Panel(
            Syntax(code, lang, theme="monokai", line_numbers=True),
            title=f"[green]Ejected to {out_path}[/green]",
            border_style="green",
        )
    )
    console.print(f"\n[green]SDK scaffold written to[/green] [bold]{out_path}[/bold]")
    console.print("[dim]Edit the file to add custom routing, middleware, and hooks.[/dim]")
