"""agentbreeder init — scaffold a new agent project.

Interactive wizard that creates a deployable agent project in seconds.
Supports all six frameworks with working example code.
"""

from __future__ import annotations

import asyncio
import os
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule
from rich.table import Table

from engine.config_parser import validate_config
from engine.providers.models import ProviderConfig, ProviderType
from engine.providers.ollama_provider import OllamaProvider

console = Console()

# ─── Framework metadata ─────────────────────────────────────────────

FRAMEWORKS = [
    {
        "key": "langgraph",
        "name": "LangGraph",
        "icon": "🕸️",
        "tagline": "Stateful multi-actor workflows",
        "model": "gpt-4o",
    },
    {
        "key": "crewai",
        "name": "CrewAI",
        "icon": "👥",
        "tagline": "Role-playing agent crews",
        "model": "gpt-4o",
    },
    {
        "key": "claude_sdk",
        "name": "Claude SDK",
        "icon": "🎭",
        "tagline": "Anthropic's native agent SDK",
        "model": "claude-sonnet-4-20250514",
    },
    {
        "key": "openai_agents",
        "name": "OpenAI Agents",
        "icon": "🤖",
        "tagline": "OpenAI's agent framework",
        "model": "gpt-4o",
    },
    {
        "key": "google_adk",
        "name": "Google ADK",
        "icon": "🔷",
        "tagline": "Google's Agent Development Kit",
        "model": "gemini-2.0-flash",
    },
    {
        "key": "custom",
        "name": "Custom",
        "icon": "⚙️",
        "tagline": "Bring your own agent code",
        "model": "gpt-4o",
    },
]

# ─── Node.js framework metadata ─────────────────────────────────────

NODE_FRAMEWORKS = [
    {
        "key": "vercel-ai",
        "name": "Vercel AI SDK",
        "icon": "▲",
        "tagline": "Streaming-first AI framework by Vercel",
        "model": "gpt-4o",
    },
    {
        "key": "mastra",
        "name": "Mastra",
        "icon": "🔮",
        "tagline": "TypeScript agent framework by Mastra",
        "model": "gpt-4o",
    },
    {
        "key": "langchain-js",
        "name": "LangChain.js",
        "icon": "🦜",
        "tagline": "LangChain for TypeScript/JavaScript",
        "model": "gpt-4o",
    },
    {
        "key": "openai-agents-ts",
        "name": "OpenAI Agents (TS)",
        "icon": "🤖",
        "tagline": "OpenAI Agents SDK for TypeScript",
        "model": "gpt-4o",
    },
    {
        "key": "deepagent",
        "name": "DeepAgent",
        "icon": "🔬",
        "tagline": "Research-focused TypeScript agent framework",
        "model": "gpt-4o",
    },
    {
        "key": "custom",
        "name": "Custom",
        "icon": "⚙️",
        "tagline": "Bring your own TypeScript agent code",
        "model": "gpt-4o",
    },
]

# ─── MCP server framework metadata ──────────────────────────────────

MCP_FRAMEWORKS_NODE = [
    {
        "key": "mcp-ts",
        "name": "MCP TypeScript SDK",
        "icon": "🔧",
        "tagline": "Official MCP SDK for TypeScript",
        "model": "",
    },
]

MCP_FRAMEWORKS_PYTHON = [
    {
        "key": "mcp-py",
        "name": "MCP Python SDK",
        "icon": "🔧",
        "tagline": "Official MCP SDK for Python",
        "model": "",
    },
]

CLOUDS = [
    {"key": "local", "name": "Local", "icon": "💻", "tagline": "Docker Compose on your machine"},
    {"key": "aws", "name": "AWS", "icon": "☁️", "tagline": "ECS Fargate / Lambda / EKS"},
    {"key": "gcp", "name": "GCP", "icon": "🌐", "tagline": "Cloud Run / GKE / Functions"},
    {"key": "kubernetes", "name": "Kubernetes", "icon": "⎈", "tagline": "Any K8s cluster"},
]


# ─── Template generators ────────────────────────────────────────────


def _agent_yaml(name: str, framework: str, cloud: str, model: str, team: str, owner: str) -> str:
    return f"""\
# AgentBreeder configuration — generated by `agentbreeder init`
# Docs: https://github.com/agentbreeder/agentbreeder

name: {name}
version: 0.1.0
description: "{name} — powered by {framework}"
team: {team}
owner: {owner}
tags:
  - {framework}
  - generated

framework: {framework}

model:
  primary: {model}

deploy:
  cloud: {cloud}
"""


def _env_example(framework: str) -> str:
    lines = [
        "# Environment variables for your agent",
        "# Copy this to .env and fill in your values",
        "",
        "AGENTBREEDER_ENV=development",
    ]

    if framework in ("langgraph", "openai_agents"):
        lines.append("OPENAI_API_KEY=sk-...")
    elif framework == "claude_sdk":
        lines.append("ANTHROPIC_API_KEY=sk-ant-...")
    elif framework == "google_adk":
        lines.append("GOOGLE_API_KEY=...")
    elif framework == "crewai":
        lines.append("OPENAI_API_KEY=sk-...")
    else:
        lines.append("# Add your API keys here")

    return "\n".join(lines) + "\n"


def _requirements(framework: str) -> str:
    base = ["agentbreeder-sdk>=0.1.0"]

    deps = {
        "langgraph": ["langgraph>=0.2.0", "langchain-openai>=0.1.0"],
        "crewai": ["crewai>=0.41.0", "crewai-tools>=0.8.0"],
        "claude_sdk": ["anthropic>=0.39.0"],
        "openai_agents": ["openai-agents>=0.1.0"],
        "google_adk": ["google-adk>=0.1.0"],
        "custom": [],
    }

    return "\n".join(base + deps.get(framework, [])) + "\n"


def _agent_py_langgraph(name: str) -> str:
    return f'''\
"""{name} — LangGraph agent.

A simple stateful agent with tool-calling capability.
The model is set by the AGENT_MODEL environment variable (injected by agentbreeder deploy).
"""

import os
from typing import Annotated, TypedDict

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages


class State(TypedDict):
    messages: Annotated[list, add_messages]


def _build_llm():
    model = os.environ.get("AGENT_MODEL", "gpt-4o")
    if model.startswith("ollama/"):
        from langchain_ollama import ChatOllama
        ollama_base = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
        return ChatOllama(model=model.split("/", 1)[1], base_url=ollama_base)
    if model.startswith("claude"):
        from langchain_anthropic import ChatAnthropic
        return ChatAnthropic(model=model)
    if model.startswith("gemini"):
        from langchain_google_genai import ChatGoogleGenerativeAI
        return ChatGoogleGenerativeAI(model=model)
    from langchain_openai import ChatOpenAI
    return ChatOpenAI(model=model)


llm = _build_llm()


def chatbot(state: State) -> dict:
    """Process the current state and generate a response."""
    return {{"messages": [llm.invoke(state["messages"])]}}


# Build the graph
graph = StateGraph(State)
graph.add_node("chatbot", chatbot)
graph.add_edge(START, "chatbot")
graph.add_edge("chatbot", END)

app = graph.compile()

if __name__ == "__main__":
    result = app.invoke({{"messages": [{{"role": "user", "content": "Hello!"}}]}})
    print(result["messages"][-1].content)
'''


def _agent_py_crewai(name: str) -> str:
    return f'''\
"""{name} — CrewAI agent.

A simple crew with a researcher and writer agent.
"""

from crewai import Agent, Crew, Task


researcher = Agent(
    role="Researcher",
    goal="Find accurate, up-to-date information",
    backstory="You are a meticulous researcher who verifies every fact.",
    verbose=True,
)

writer = Agent(
    role="Writer",
    goal="Create clear, concise summaries",
    backstory="You turn complex research into readable prose.",
    verbose=True,
)


def run(topic: str = "AI agents in 2026") -> str:
    """Run the crew on a topic."""
    research_task = Task(
        description=f"Research the topic: {{topic}}",
        expected_output="A detailed factual summary with key findings.",
        agent=researcher,
    )
    write_task = Task(
        description="Write a clear summary based on the research.",
        expected_output="A 2-3 paragraph summary suitable for a blog post.",
        agent=writer,
    )
    crew = Crew(agents=[researcher, writer], tasks=[research_task, write_task])
    return crew.kickoff()


if __name__ == "__main__":
    result = run()
    print(result)
'''


def _agent_py_claude_sdk(name: str) -> str:
    return f'''\
"""{name} — Claude SDK agent.

A simple tool-using agent powered by Anthropic's Claude.
"""

import anthropic


client = anthropic.Anthropic()

tools = [
    {{
        "name": "get_weather",
        "description": "Get current weather for a city.",
        "input_schema": {{
            "type": "object",
            "properties": {{
                "city": {{"type": "string", "description": "City name"}},
            }},
            "required": ["city"],
        }},
    }}
]


def get_weather(city: str) -> str:
    """Stub tool — replace with real implementation."""
    return f"Sunny, 22°C in {{city}}"


def run(user_message: str = "What's the weather in Tokyo?") -> str:
    """Run the agent with a user message."""
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        tools=tools,
        messages=[{{"role": "user", "content": user_message}}],
    )

    # Handle tool use
    for block in response.content:
        if block.type == "tool_use" and block.name == "get_weather":
            tool_result = get_weather(block.input["city"])
            # Send tool result back
            follow_up = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=1024,
                tools=tools,
                messages=[
                    {{"role": "user", "content": user_message}},
                    {{"role": "assistant", "content": response.content}},
                    {{"role": "user", "content": [
                        {{"type": "tool_result", "tool_use_id": block.id, "content": tool_result}}
                    ]}},
                ],
            )
            return follow_up.content[0].text

    return response.content[0].text


if __name__ == "__main__":
    print(run())
'''


def _agent_py_openai_agents(name: str) -> str:
    return f'''\
"""{name} — OpenAI Agents SDK agent.

A simple agent using the OpenAI Agents framework.
"""

from agents import Agent, Runner


agent = Agent(
    name="{name}",
    instructions="You are a helpful assistant. Be concise and accurate.",
)


def run(user_message: str = "Hello!") -> str:
    """Run the agent with a user message."""
    result = Runner.run_sync(agent, user_message)
    return result.final_output


if __name__ == "__main__":
    print(run())
'''


def _agent_py_google_adk(name: str) -> str:
    return f'''\
"""{name} — Google ADK agent.

A simple agent using Google's Agent Development Kit.
"""

from google.adk.agents import Agent


agent = Agent(
    model="gemini-2.0-flash",
    name="{name}",
    instruction="You are a helpful assistant. Be concise and accurate.",
)


if __name__ == "__main__":
    # ADK agents are typically served via `adk web` or `adk api_server`
    print(f"Agent '{{agent.name}}' ready. Run with: adk web")
'''


def _agent_py_custom(name: str) -> str:
    return f'''\
"""{name} — Custom agent.

Replace this with your own agent implementation.
The only requirement: expose an `invoke(input)` function or HTTP endpoint.
"""


def invoke(input_data: dict) -> dict:
    """Process an input and return a response.

    This is the entry point that AgentBreeder will call.
    """
    message = input_data.get("message", "")
    return {{
        "response": f"Echo: {{message}}",
        "agent": "{name}",
    }}


if __name__ == "__main__":
    result = invoke({{"message": "Hello from {name}!"}})
    print(result["response"])
'''


AGENT_PY_GENERATORS = {
    "langgraph": _agent_py_langgraph,
    "crewai": _agent_py_crewai,
    "claude_sdk": _agent_py_claude_sdk,
    "openai_agents": _agent_py_openai_agents,
    "google_adk": _agent_py_google_adk,
    "custom": _agent_py_custom,
}


# ─── Node agent template generators ─────────────────────────────────


def _agent_ts(name: str, framework: str) -> str:
    """Generate agent.ts for a Node agent."""
    return """\
// agent.ts — Your agent logic. This is the only file you need to edit.
// Platform-managed files (server.ts, Dockerfile) are generated at deploy time.
import { openai } from '@ai-sdk/openai'

export const model = openai('gpt-4o')
export const systemPrompt = `You are a helpful assistant.`
// Optional additional tools beyond APS-injected tools
export const tools = {}
"""


def _agent_yaml_node(name: str, framework: str, cloud: str) -> str:
    """Generate agent.yaml for a Node agent."""
    return f"""\
name: {name}
version: 1.0.0
team: my-team
owner: engineer@company.com

model:
  primary: gpt-4o

runtime:
  language: node
  framework: {framework}
  version: "20"

deploy:
  cloud: {cloud}
"""


def _package_json(name: str) -> str:
    """Generate package.json for a Node agent."""
    return (
        """\
{
  "name": \""""
        + name
        + """\",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node --loader ts-node/esm server.ts"
  },
  "dependencies": {
    "@agentbreeder/aps-client": "^0.1.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.4.0"
  }
}
"""
    )


def _tsconfig_json() -> str:
    """Generate tsconfig.json for a Node agent or MCP server."""
    return """\
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true
  }
}
"""


def _gitignore_node() -> str:
    """Generate .gitignore for a Node project."""
    return """\
node_modules/
dist/
.env
*.js.map
"""


# ─── MCP server template generators ─────────────────────────────────


def _tools_ts(name: str) -> str:
    """Generate tools.ts for a TypeScript MCP server."""
    return """\
// tools.ts — Your MCP tool implementations.
// Export one async function per tool.

export async function search_web({ query }: { query: string }): Promise<string> {
  // TODO: implement your search logic
  return `Search results for: ${query}`
}
"""


def _mcp_server_yaml_node(name: str) -> str:
    """Generate mcp-server.yaml for a TypeScript MCP server."""
    return f"""\
name: {name}
version: 1.0.0
type: mcp-server
team: my-team
owner: engineer@company.com

runtime:
  language: node
  framework: mcp-ts
  version: "20"

transport: http

tools:
  - name: search_web
    description: "Search the web"
    schema:
      type: object
      properties:
        query: {{type: string}}
      required: [query]
"""


def _tools_py(name: str) -> str:
    """Generate tools.py for a Python MCP server."""
    return f'''\
"""tools.py — Your MCP tool implementations for {name}.

Each function decorated with @mcp.tool() becomes an MCP tool.
"""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{name}")


@mcp.tool()
def search_web(query: str) -> str:
    """Search the web.

    Args:
        query: The search query string.

    Returns:
        A string with search results.
    """
    # TODO: implement your search logic
    return f"Search results for: {{query}}"


if __name__ == "__main__":
    mcp.run()
'''


def _mcp_server_yaml_python(name: str) -> str:
    """Generate mcp-server.yaml for a Python MCP server."""
    return f"""\
name: {name}
version: 1.0.0
type: mcp-server
team: my-team
owner: engineer@company.com

runtime:
  language: python
  framework: mcp-py
  version: "3.11"

transport: http

tools:
  - name: search_web
    description: "Search the web"
    schema:
      type: object
      properties:
        query: {{type: string}}
      required: [query]
"""


def _readme(name: str, framework: str, cloud: str) -> str:
    fw = next((f for f in FRAMEWORKS if f["key"] == framework), FRAMEWORKS[0])
    return f"""\
# {name}

{fw["icon"]} **{fw["name"]}** agent — scaffolded by AgentBreeder.

## Quick Start

```bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Set up environment
cp .env.example .env
# Edit .env with your API keys

# 3. Test locally
python agent.py

# 4. Validate config
agentbreeder validate agent.yaml

# 5. Deploy
agentbreeder deploy agent.yaml --target {cloud}
```

## Project Structure

```
{name}/
├── agent.yaml        # AgentBreeder configuration
├── agent.py          # Your agent code
├── requirements.txt  # Python dependencies
├── .env.example      # Environment template
└── README.md         # This file
```

## Learn More

- [AgentBreeder Docs](https://github.com/agentbreeder/agentbreeder)
- [{fw["name"]} Docs](https://github.com/agentbreeder/agentbreeder#frameworks)
"""


# ─── Selection UI helpers ────────────────────────────────────────────


def _show_selection(title: str, items: list[dict], selected: int) -> None:
    """Render a selection menu with the selected item highlighted."""
    table = Table(
        show_header=False,
        show_edge=False,
        box=None,
        padding=(0, 2),
    )
    table.add_column(width=3)
    table.add_column(width=3)
    table.add_column(width=20)
    table.add_column()

    for i, item in enumerate(items):
        num = str(i + 1)
        if i == selected:
            table.add_row(
                "[bold cyan]›[/bold cyan]",
                item["icon"],
                f"[bold cyan]{item['name']}[/bold cyan]",
                f"[dim cyan]{item['tagline']}[/dim cyan]",
            )
        else:
            table.add_row(
                f"[dim]{num}[/dim]",
                item["icon"],
                item["name"],
                f"[dim]{item['tagline']}[/dim]",
            )

    console.print(f"\n  [bold]{title}[/bold]\n")
    console.print(table)


def _prompt_selection(title: str, items: list[dict]) -> dict:
    """Prompt the user to select from a numbered list."""
    _show_selection(title, items, selected=-1)

    while True:
        console.print()
        raw = console.input(f"  [bold]Enter number (1-{len(items)}): [/bold]")
        try:
            choice = int(raw.strip())
            if 1 <= choice <= len(items):
                selected = items[choice - 1]
                console.print(f"  [green]✓[/green] {selected['icon']} {selected['name']}")
                return selected
        except ValueError:
            pass
        console.print(f"  [red]Please enter a number between 1 and {len(items)}[/red]")


def _prompt_text(
    label: str,
    default: str = "",
    validate_fn: Callable[..., Any] | None = None,
) -> str:
    """Prompt for text input with optional validation."""
    while True:
        if default:
            raw = console.input(f"  [bold]{label}[/bold] [dim]({default})[/dim]: ")
            value = raw.strip() or default
        else:
            raw = console.input(f"  [bold]{label}[/bold]: ")
            value = raw.strip()

        if not value:
            console.print("  [red]This field is required[/red]")
            continue

        if validate_fn:
            error = validate_fn(value)
            if error:
                console.print(f"  [red]{error}[/red]")
                continue

        console.print(f"  [green]✓[/green] {value}")
        return value


def _validate_agent_name(name: str) -> str | None:
    """Validate an agent name. Returns error message or None."""
    if len(name) < 2:
        return "Name must be at least 2 characters"
    if not re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$", name):
        return "Must be lowercase alphanumeric with hyphens (e.g., 'my-agent')"
    return None


def _validate_email(email: str) -> str | None:
    """Basic email validation. Returns error message or None."""
    if "@" not in email or "." not in email.split("@")[-1]:
        return "Please enter a valid email address"
    return None


def _gather_model_suggestions() -> list[str]:
    """Collect up to 5 model suggestions from locally available providers.

    Returns a list of model strings formatted as 'ollama/<name>' or
    'openrouter/<provider>/<model>'.  Returns an empty list when neither
    Ollama nor OpenRouter is reachable.
    """
    suggestions: list[str] = []

    # --- Ollama ---
    async def _fetch_ollama() -> list[str]:
        if not await OllamaProvider.detect():
            return []
        provider = OllamaProvider(ProviderConfig(provider_type=ProviderType.ollama))
        try:
            models = await provider.list_models()
            return [f"ollama/{m.name}" for m in models]
        finally:
            await provider.close()

    try:
        ollama_names = asyncio.run(_fetch_ollama())
        suggestions.extend(ollama_names[: 5 - len(suggestions)])
    except Exception:
        pass

    # --- OpenRouter (use cached registry scan if available) ---
    if len(suggestions) < 5 and os.environ.get("OPENROUTER_API_KEY"):
        registry_path = Path.home() / ".agentbreeder" / "registry" / "models.json"
        if registry_path.exists():
            try:
                import json

                registry: dict = json.loads(registry_path.read_text())
                or_entries = [v for v in registry.values() if v.get("source") == "openrouter"]
                for entry in or_entries[: 5 - len(suggestions)]:
                    model_id: str = entry.get("name", "")
                    if model_id:
                        suggestions.append(f"openrouter/{model_id}")
            except Exception:
                pass

    return suggestions[:5]


def _prompt_model_suggestion(default_model: str) -> str:
    """Show local model suggestions and let the user pick one or keep the default.

    Returns the chosen model string (either a suggestion or *default_model*).
    """
    suggestions = _gather_model_suggestions()
    if not suggestions:
        return default_model

    console.print("\n  [bold]Model suggestions (from local providers)[/bold]\n")
    for i, model in enumerate(suggestions, start=1):
        console.print(f"  [dim]{i}.[/dim] {model}")
    keep_num = len(suggestions) + 1
    console.print(f"  [dim]{keep_num}.[/dim] Keep default ([dim]{default_model}[/dim])")

    while True:
        console.print()
        raw = console.input(f"  [bold]Enter number (1-{keep_num}): [/bold]").strip()
        try:
            choice = int(raw)
            if choice == keep_num:
                console.print(f"  [green]✓[/green] {default_model}")
                return default_model
            if 1 <= choice <= len(suggestions):
                selected = suggestions[choice - 1]
                console.print(f"  [green]✓[/green] {selected}")
                return selected
        except ValueError:
            pass
        console.print(f"  [red]Please enter a number between 1 and {keep_num}[/red]")


# ─── Scaffold helpers ────────────────────────────────────────────────


def _gather_project_details(
    output_dir: str | None, json_output: bool
) -> tuple[str, str, str, Path]:
    """Prompt for name, team, owner, and resolve project_dir.

    Returns (name, team, owner, project_dir).
    """
    console.print("\n  [bold]Project details[/bold]\n")

    cwd_name = Path.cwd().name
    default_name = re.sub(r"[^a-z0-9-]", "-", cwd_name.lower()).strip("-") or "my-agent"
    if len(default_name) < 2:
        default_name = "my-agent"

    name = _prompt_text("Agent name", default=default_name, validate_fn=_validate_agent_name)
    team = _prompt_text("Team", default="engineering")

    # Try to get a sensible email default from git config
    git_email = ""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "config", "user.email"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            git_email = result.stdout.strip()
    except Exception:
        pass

    owner = _prompt_text("Owner email", default=git_email, validate_fn=_validate_email)

    project_dir = Path(output_dir) if output_dir else Path.cwd() / name
    project_dir = project_dir.resolve()

    return name, team, owner, project_dir


def _check_and_create_dir(project_dir: Path) -> None:
    """Warn if project_dir is non-empty; abort or continue based on user input."""
    if project_dir.exists() and any(project_dir.iterdir()):
        console.print(
            f"\n  [yellow]Warning:[/yellow] Directory [bold]{project_dir}[/bold] is not empty."
        )
        overwrite = console.input("  [bold]Continue anyway? (y/N): [/bold]").strip().lower()
        if overwrite != "y":
            console.print("  [dim]Aborted.[/dim]")
            raise typer.Exit(code=0)

    project_dir.mkdir(parents=True, exist_ok=True)


def _write_files(files: dict[str, str], project_dir: Path, json_output: bool) -> list[str]:
    """Write all files and return list of created file paths."""
    if not json_output:
        console.print()
        console.print(Rule(style="dim"))
        console.print()

    created_files = []
    for filename, content in files.items():
        filepath = project_dir / filename
        filepath.write_text(content)
        created_files.append(str(filepath))
        if not json_output:
            console.print(f"  [green]✓[/green] {filename}")
    return created_files


def _show_next_steps_python(
    name: str,
    framework: dict,
    cloud: dict,
    project_dir: Path,
    validation: object,
    json_output: bool,
    created_files: list[str],
    team: str,
    owner: str,
) -> None:
    """Print validation result and next steps for Python agents."""
    yaml_path = project_dir / "agent.yaml"
    validation = validate_config(yaml_path)

    if json_output:
        import json
        import sys

        output = {
            "project_dir": str(project_dir),
            "name": name,
            "framework": framework["key"],
            "cloud": cloud["key"],
            "team": team,
            "owner": owner,
            "files": created_files,
            "valid": validation.valid,
        }
        if not validation.valid:
            output["validation_errors"] = [e.model_dump() for e in validation.errors]
        sys.stdout.write(json.dumps(output, indent=2) + "\n")
        return

    console.print()

    if validation.valid:
        console.print("  [green]✓[/green] agent.yaml validated")
    else:
        console.print("  [yellow]⚠[/yellow] agent.yaml has validation warnings:")
        for err in validation.errors:
            console.print(f"    [dim]- {err.path}: {err.message}[/dim]")

    rel_dir = os.path.relpath(project_dir, Path.cwd())
    if rel_dir == ".":
        cd_cmd = ""
    elif rel_dir.startswith(".."):
        cd_cmd = f"cd {project_dir}\n  "
    else:
        cd_cmd = f"cd {rel_dir}\n  "

    console.print()
    console.print(
        Panel(
            f"[bold green]Project created![/bold green] {framework['icon']} {name}\n\n"
            f"  [bold]Next steps:[/bold]\n\n"
            f"  [dim]$[/dim] {cd_cmd}pip install -r requirements.txt\n"
            f"  [dim]$[/dim] cp .env.example .env\n"
            f"  [dim]$[/dim] [dim]# Add your API keys to .env[/dim]\n"
            f"  [dim]$[/dim] python agent.py\n"
            f"  [dim]$[/dim] agentbreeder validate agent.yaml\n"
            f"  [dim]$[/dim] agentbreeder deploy agent.yaml --target {cloud['key']}",
            title="Ready",
            border_style="green",
            padding=(1, 2),
        )
    )
    console.print()


def _show_next_steps_node(
    name: str,
    framework_key: str,
    cloud_key: str,
    project_dir: Path,
    json_output: bool,
    created_files: list[str],
    agent_type: str,
) -> None:
    """Print next steps for Node agents and MCP servers (no YAML validation for these)."""
    if json_output:
        import json
        import sys

        output = {
            "project_dir": str(project_dir),
            "name": name,
            "framework": framework_key,
            "cloud": cloud_key,
            "language": "node",
            "type": agent_type,
            "files": created_files,
        }
        sys.stdout.write(json.dumps(output, indent=2) + "\n")
        return

    console.print()

    rel_dir = os.path.relpath(project_dir, Path.cwd())
    if rel_dir == ".":
        cd_cmd = ""
    elif rel_dir.startswith(".."):
        cd_cmd = f"cd {project_dir}\n  "
    else:
        cd_cmd = f"cd {rel_dir}\n  "

    console.print()
    console.print(
        Panel(
            f"[bold green]Project created![/bold green] {name}\n\n"
            f"  [bold]Next steps:[/bold]\n\n"
            f"  [dim]$[/dim] {cd_cmd}npm install\n"
            f"  [dim]$[/dim] agentbreeder validate agent.yaml\n"
            f"  [dim]$[/dim] agentbreeder deploy agent.yaml --target {cloud_key}",
            title="Ready",
            border_style="green",
            padding=(1, 2),
        )
    )
    console.print()


def _scaffold_python(
    output_dir: str | None,
    framework_key: str | None,
    agent_type: str,
    json_output: bool,
) -> None:
    """Scaffold a Python agent (existing behavior, unchanged)."""
    if not json_output:
        console.print()
        console.print(
            Panel(
                "[bold]New Agent Project[/bold]\n"
                "[dim]Answer a few questions and you'll have a deployable agent in seconds.[/dim]",
                title="[bold]AgentBreeder[/bold]",
                border_style="blue",
                padding=(1, 2),
            )
        )

    # MCP server path
    if agent_type == "mcp-server":
        name, team, owner, project_dir = _gather_project_details(output_dir, json_output)
        _check_and_create_dir(project_dir)

        files = {
            "tools.py": _tools_py(name),
            "mcp-server.yaml": _mcp_server_yaml_python(name),
            "requirements.txt": "mcp>=1.0.0\n",
        }
        created_files = _write_files(files, project_dir, json_output)

        if json_output:
            import json
            import sys

            output = {
                "project_dir": str(project_dir),
                "name": name,
                "framework": "mcp-py",
                "language": "python",
                "type": "mcp-server",
                "files": created_files,
            }
            sys.stdout.write(json.dumps(output, indent=2) + "\n")
            return

        console.print()
        console.print(
            Panel(
                f"[bold green]MCP server created![/bold green] {name}\n\n"
                f"  [bold]Next steps:[/bold]\n\n"
                f"  [dim]$[/dim] pip install -r requirements.txt\n"
                f"  [dim]$[/dim] python tools.py",
                title="Ready",
                border_style="green",
                padding=(1, 2),
            )
        )
        console.print()
        return

    # Standard Python agent path
    # ── Step 1: Framework ────────────────────────────────────────
    framework = _prompt_selection("What framework?", FRAMEWORKS)

    # ── Step 2: Cloud ────────────────────────────────────────────
    cloud = _prompt_selection("Where will it run?", CLOUDS)

    # ── Step 2b: Model (optional local provider suggestions) ────
    if cloud["key"] == "local":
        local_suggestions = _gather_model_suggestions()
        if local_suggestions:
            framework = {**framework, "model": local_suggestions[0]}
    if not json_output:
        framework["model"] = _prompt_model_suggestion(framework["model"])

    # ── Step 3: Details ──────────────────────────────────────────
    name, team, owner, project_dir = _gather_project_details(output_dir, json_output)
    _check_and_create_dir(project_dir)

    files = {
        "agent.yaml": _agent_yaml(
            name=name,
            framework=framework["key"],
            cloud=cloud["key"],
            model=framework["model"],
            team=team,
            owner=owner,
        ),
        "agent.py": AGENT_PY_GENERATORS[framework["key"]](name),
        "requirements.txt": _requirements(framework["key"]),
        ".env.example": _env_example(framework["key"]),
        "README.md": _readme(name, framework["key"], cloud["key"]),
    }

    created_files = _write_files(files, project_dir, json_output)
    _show_next_steps_python(
        name=name,
        framework=framework,
        cloud=cloud,
        project_dir=project_dir,
        validation=None,
        json_output=json_output,
        created_files=created_files,
        team=team,
        owner=owner,
    )


def _scaffold_node(
    output_dir: str | None,
    framework_key: str | None,
    agent_type: str,
    json_output: bool,
) -> None:
    """Scaffold a Node.js agent or MCP server."""
    if not json_output:
        console.print()
        console.print(
            Panel(
                "[bold]New Node.js Project[/bold]\n"
                "[dim]Answer a few questions and you'll have a deployable TypeScript project in seconds.[/dim]",
                title="[bold]AgentBreeder[/bold]",
                border_style="blue",
                padding=(1, 2),
            )
        )

    if agent_type == "mcp-server":
        # MCP server — use mcp-ts framework, no interactive framework picker needed
        fw_key = framework_key or "mcp-ts"
        cloud_key = "local"

        name, _team, _owner, project_dir = _gather_project_details(output_dir, json_output)
        _check_and_create_dir(project_dir)

        files = {
            "tools.ts": _tools_ts(name),
            "mcp-server.yaml": _mcp_server_yaml_node(name),
            "package.json": _package_json(name),
            "tsconfig.json": _tsconfig_json(),
            ".gitignore": _gitignore_node(),
        }
        created_files = _write_files(files, project_dir, json_output)
        _show_next_steps_node(
            name=name,
            framework_key=fw_key,
            cloud_key=cloud_key,
            project_dir=project_dir,
            json_output=json_output,
            created_files=created_files,
            agent_type=agent_type,
        )
        return

    # Standard Node agent
    if framework_key:
        # Framework was passed via --framework flag; find it in NODE_FRAMEWORKS
        fw = next((f for f in NODE_FRAMEWORKS if f["key"] == framework_key), None)
        if fw is None:
            console.print(
                f"[red]Unknown Node framework: {framework_key}. "
                f"Choose: {', '.join(f['key'] for f in NODE_FRAMEWORKS)}[/red]"
            )
            raise typer.Exit(code=1)
    else:
        fw = _prompt_selection("What Node.js framework?", NODE_FRAMEWORKS)

    # ── Cloud ──────────────────────────────────────────────────
    cloud = _prompt_selection("Where will it run?", CLOUDS)

    name, _team, _owner, project_dir = _gather_project_details(output_dir, json_output)
    _check_and_create_dir(project_dir)

    files = {
        "agent.ts": _agent_ts(name, fw["key"]),
        "agent.yaml": _agent_yaml_node(name, fw["key"], cloud["key"]),
        "package.json": _package_json(name),
        "tsconfig.json": _tsconfig_json(),
        ".gitignore": _gitignore_node(),
    }
    created_files = _write_files(files, project_dir, json_output)
    _show_next_steps_node(
        name=name,
        framework_key=fw["key"],
        cloud_key=cloud["key"],
        project_dir=project_dir,
        json_output=json_output,
        created_files=created_files,
        agent_type=agent_type,
    )


# ─── Main command ────────────────────────────────────────────────────


def init(
    output_dir: str = typer.Argument(
        None,
        help="Directory to create the project in (defaults to agent name)",
    ),
    json_output: bool = typer.Option(
        False,
        "--json",
        help="Output as JSON (for CI/scripting)",
    ),
    language: str = typer.Option(
        "python",
        "--language",
        help="Language runtime: python | node",
    ),
    agent_type: str = typer.Option(
        "agent",
        "--type",
        help="Project type: agent | mcp-server",
    ),
    framework: str | None = typer.Option(
        None,
        "--framework",
        help="Framework to use (skips interactive picker)",
    ),
) -> None:
    """Scaffold a new agent or MCP server project.

    Creates a complete, deployable project. Use --language to choose Python
    (default) or Node.js. Use --type to scaffold an agent (default) or an
    MCP server.

    Examples:

      agentbreeder init --name my-agent --framework langgraph

      agentbreeder init --language node --framework vercel-ai --name my-ts-agent

      agentbreeder init --type mcp-server --language node --name my-tools

      agentbreeder init --type mcp-server --language python --name my-tools
    """
    if language not in ("python", "node"):
        console.print(f"[red]Unknown language: {language}. Choose: python, node[/red]")
        raise typer.Exit(code=1)

    if agent_type not in ("agent", "mcp-server"):
        console.print(f"[red]Unknown type: {agent_type}. Choose: agent, mcp-server[/red]")
        raise typer.Exit(code=1)

    if language == "node":
        _scaffold_node(
            output_dir=output_dir,
            framework_key=framework,
            agent_type=agent_type,
            json_output=json_output,
        )
    else:
        _scaffold_python(
            output_dir=output_dir,
            framework_key=framework,
            agent_type=agent_type,
            json_output=json_output,
        )
