"""agentbreeder init — scaffold a new agent project.

Interactive wizard that creates a deployable agent project in seconds.
Supports all six frameworks with working example code.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule
from rich.table import Table

from engine.config_parser import validate_config

console = Console()

# ─── Framework metadata ─────────────────────────────────────────────

FRAMEWORKS = [
    {
        "key": "langgraph",
        "name": "LangGraph",
        "icon": "🕸️",
        "tagline": "Stateful multi-actor workflows",
        "model": "gpt-4o",
    },
    {
        "key": "crewai",
        "name": "CrewAI",
        "icon": "👥",
        "tagline": "Role-playing agent crews",
        "model": "gpt-4o",
    },
    {
        "key": "claude_sdk",
        "name": "Claude SDK",
        "icon": "🎭",
        "tagline": "Anthropic's native agent SDK",
        "model": "claude-sonnet-4-20250514",
    },
    {
        "key": "openai_agents",
        "name": "OpenAI Agents",
        "icon": "🤖",
        "tagline": "OpenAI's agent framework",
        "model": "gpt-4o",
    },
    {
        "key": "google_adk",
        "name": "Google ADK",
        "icon": "🔷",
        "tagline": "Google's Agent Development Kit",
        "model": "gemini-2.0-flash",
    },
    {
        "key": "custom",
        "name": "Custom",
        "icon": "⚙️",
        "tagline": "Bring your own agent code",
        "model": "gpt-4o",
    },
]

CLOUDS = [
    {"key": "local", "name": "Local", "icon": "💻", "tagline": "Docker Compose on your machine"},
    {"key": "aws", "name": "AWS", "icon": "☁️", "tagline": "ECS Fargate / Lambda / EKS"},
    {"key": "gcp", "name": "GCP", "icon": "🌐", "tagline": "Cloud Run / GKE / Functions"},
    {"key": "kubernetes", "name": "Kubernetes", "icon": "⎈", "tagline": "Any K8s cluster"},
]


# ─── Template generators ────────────────────────────────────────────


def _agent_yaml(name: str, framework: str, cloud: str, model: str, team: str, owner: str) -> str:
    return f"""\
# AgentBreeder configuration — generated by `agentbreeder init`
# Docs: https://github.com/open-agent-garden/agentbreeder

name: {name}
version: 0.1.0
description: "{name} — powered by {framework}"
team: {team}
owner: {owner}
tags:
  - {framework}
  - generated

framework: {framework}

model:
  primary: {model}

deploy:
  cloud: {cloud}
"""


def _env_example(framework: str) -> str:
    lines = [
        "# Environment variables for your agent",
        "# Copy this to .env and fill in your values",
        "",
        "GARDEN_ENV=development",
    ]

    if framework in ("langgraph", "openai_agents"):
        lines.append("OPENAI_API_KEY=sk-...")
    elif framework == "claude_sdk":
        lines.append("ANTHROPIC_API_KEY=sk-ant-...")
    elif framework == "google_adk":
        lines.append("GOOGLE_API_KEY=...")
    elif framework == "crewai":
        lines.append("OPENAI_API_KEY=sk-...")
    else:
        lines.append("# Add your API keys here")

    return "\n".join(lines) + "\n"


def _requirements(framework: str) -> str:
    base = ["agentbreeder-sdk>=0.1.0"]

    deps = {
        "langgraph": ["langgraph>=0.2.0", "langchain-openai>=0.1.0"],
        "crewai": ["crewai>=0.41.0", "crewai-tools>=0.8.0"],
        "claude_sdk": ["anthropic>=0.39.0"],
        "openai_agents": ["openai-agents>=0.1.0"],
        "google_adk": ["google-adk>=0.1.0"],
        "custom": [],
    }

    return "\n".join(base + deps.get(framework, [])) + "\n"


def _agent_py_langgraph(name: str) -> str:
    return f'''\
"""{name} — LangGraph agent.

A simple stateful agent with tool-calling capability.
"""

from typing import Annotated, TypedDict

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages


class State(TypedDict):
    messages: Annotated[list, add_messages]


llm = ChatOpenAI(model="gpt-4o")


def chatbot(state: State) -> dict:
    """Process the current state and generate a response."""
    return {{"messages": [llm.invoke(state["messages"])]}}


# Build the graph
graph = StateGraph(State)
graph.add_node("chatbot", chatbot)
graph.add_edge(START, "chatbot")
graph.add_edge("chatbot", END)

app = graph.compile()

if __name__ == "__main__":
    result = app.invoke({{"messages": [{{"role": "user", "content": "Hello!"}}]}})
    print(result["messages"][-1].content)
'''


def _agent_py_crewai(name: str) -> str:
    return f'''\
"""{name} — CrewAI agent.

A simple crew with a researcher and writer agent.
"""

from crewai import Agent, Crew, Task


researcher = Agent(
    role="Researcher",
    goal="Find accurate, up-to-date information",
    backstory="You are a meticulous researcher who verifies every fact.",
    verbose=True,
)

writer = Agent(
    role="Writer",
    goal="Create clear, concise summaries",
    backstory="You turn complex research into readable prose.",
    verbose=True,
)


def run(topic: str = "AI agents in 2026") -> str:
    """Run the crew on a topic."""
    research_task = Task(
        description=f"Research the topic: {{topic}}",
        expected_output="A detailed factual summary with key findings.",
        agent=researcher,
    )
    write_task = Task(
        description="Write a clear summary based on the research.",
        expected_output="A 2-3 paragraph summary suitable for a blog post.",
        agent=writer,
    )
    crew = Crew(agents=[researcher, writer], tasks=[research_task, write_task])
    return crew.kickoff()


if __name__ == "__main__":
    result = run()
    print(result)
'''


def _agent_py_claude_sdk(name: str) -> str:
    return f'''\
"""{name} — Claude SDK agent.

A simple tool-using agent powered by Anthropic's Claude.
"""

import anthropic


client = anthropic.Anthropic()

tools = [
    {{
        "name": "get_weather",
        "description": "Get current weather for a city.",
        "input_schema": {{
            "type": "object",
            "properties": {{
                "city": {{"type": "string", "description": "City name"}},
            }},
            "required": ["city"],
        }},
    }}
]


def get_weather(city: str) -> str:
    """Stub tool — replace with real implementation."""
    return f"Sunny, 22°C in {{city}}"


def run(user_message: str = "What's the weather in Tokyo?") -> str:
    """Run the agent with a user message."""
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        tools=tools,
        messages=[{{"role": "user", "content": user_message}}],
    )

    # Handle tool use
    for block in response.content:
        if block.type == "tool_use" and block.name == "get_weather":
            tool_result = get_weather(block.input["city"])
            # Send tool result back
            follow_up = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=1024,
                tools=tools,
                messages=[
                    {{"role": "user", "content": user_message}},
                    {{"role": "assistant", "content": response.content}},
                    {{"role": "user", "content": [
                        {{"type": "tool_result", "tool_use_id": block.id, "content": tool_result}}
                    ]}},
                ],
            )
            return follow_up.content[0].text

    return response.content[0].text


if __name__ == "__main__":
    print(run())
'''


def _agent_py_openai_agents(name: str) -> str:
    return f'''\
"""{name} — OpenAI Agents SDK agent.

A simple agent using the OpenAI Agents framework.
"""

from agents import Agent, Runner


agent = Agent(
    name="{name}",
    instructions="You are a helpful assistant. Be concise and accurate.",
)


def run(user_message: str = "Hello!") -> str:
    """Run the agent with a user message."""
    result = Runner.run_sync(agent, user_message)
    return result.final_output


if __name__ == "__main__":
    print(run())
'''


def _agent_py_google_adk(name: str) -> str:
    return f'''\
"""{name} — Google ADK agent.

A simple agent using Google's Agent Development Kit.
"""

from google.adk.agents import Agent


agent = Agent(
    model="gemini-2.0-flash",
    name="{name}",
    instruction="You are a helpful assistant. Be concise and accurate.",
)


if __name__ == "__main__":
    # ADK agents are typically served via `adk web` or `adk api_server`
    print(f"Agent '{{agent.name}}' ready. Run with: adk web")
'''


def _agent_py_custom(name: str) -> str:
    return f'''\
"""{name} — Custom agent.

Replace this with your own agent implementation.
The only requirement: expose an `invoke(input)` function or HTTP endpoint.
"""


def invoke(input_data: dict) -> dict:
    """Process an input and return a response.

    This is the entry point that AgentBreeder will call.
    """
    message = input_data.get("message", "")
    return {{
        "response": f"Echo: {{message}}",
        "agent": "{name}",
    }}


if __name__ == "__main__":
    result = invoke({{"message": "Hello from {name}!"}})
    print(result["response"])
'''


AGENT_PY_GENERATORS = {
    "langgraph": _agent_py_langgraph,
    "crewai": _agent_py_crewai,
    "claude_sdk": _agent_py_claude_sdk,
    "openai_agents": _agent_py_openai_agents,
    "google_adk": _agent_py_google_adk,
    "custom": _agent_py_custom,
}


def _readme(name: str, framework: str, cloud: str) -> str:
    fw = next((f for f in FRAMEWORKS if f["key"] == framework), FRAMEWORKS[0])
    return f"""\
# {name}

{fw["icon"]} **{fw["name"]}** agent — scaffolded by AgentBreeder.

## Quick Start

```bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Set up environment
cp .env.example .env
# Edit .env with your API keys

# 3. Test locally
python agent.py

# 4. Validate config
agentbreeder validate agent.yaml

# 5. Deploy
agentbreeder deploy agent.yaml --target {cloud}
```

## Project Structure

```
{name}/
├── agent.yaml        # AgentBreeder configuration
├── agent.py          # Your agent code
├── requirements.txt  # Python dependencies
├── .env.example      # Environment template
└── README.md         # This file
```

## Learn More

- [AgentBreeder Docs](https://github.com/open-agent-garden/agentbreeder)
- [{fw["name"]} Docs](https://github.com/open-agent-garden/agentbreeder#frameworks)
"""


# ─── Selection UI helpers ────────────────────────────────────────────


def _show_selection(title: str, items: list[dict], selected: int) -> None:
    """Render a selection menu with the selected item highlighted."""
    table = Table(
        show_header=False,
        show_edge=False,
        box=None,
        padding=(0, 2),
    )
    table.add_column(width=3)
    table.add_column(width=3)
    table.add_column(width=20)
    table.add_column()

    for i, item in enumerate(items):
        num = str(i + 1)
        if i == selected:
            table.add_row(
                "[bold cyan]›[/bold cyan]",
                item["icon"],
                f"[bold cyan]{item['name']}[/bold cyan]",
                f"[dim cyan]{item['tagline']}[/dim cyan]",
            )
        else:
            table.add_row(
                f"[dim]{num}[/dim]",
                item["icon"],
                item["name"],
                f"[dim]{item['tagline']}[/dim]",
            )

    console.print(f"\n  [bold]{title}[/bold]\n")
    console.print(table)


def _prompt_selection(title: str, items: list[dict]) -> dict:
    """Prompt the user to select from a numbered list."""
    _show_selection(title, items, selected=-1)

    while True:
        console.print()
        raw = console.input(f"  [bold]Enter number (1-{len(items)}): [/bold]")
        try:
            choice = int(raw.strip())
            if 1 <= choice <= len(items):
                selected = items[choice - 1]
                console.print(f"  [green]✓[/green] {selected['icon']} {selected['name']}")
                return selected
        except ValueError:
            pass
        console.print(f"  [red]Please enter a number between 1 and {len(items)}[/red]")


def _prompt_text(
    label: str,
    default: str = "",
    validate_fn: Callable[..., Any] | None = None,
) -> str:
    """Prompt for text input with optional validation."""
    while True:
        if default:
            raw = console.input(f"  [bold]{label}[/bold] [dim]({default})[/dim]: ")
            value = raw.strip() or default
        else:
            raw = console.input(f"  [bold]{label}[/bold]: ")
            value = raw.strip()

        if not value:
            console.print("  [red]This field is required[/red]")
            continue

        if validate_fn:
            error = validate_fn(value)
            if error:
                console.print(f"  [red]{error}[/red]")
                continue

        console.print(f"  [green]✓[/green] {value}")
        return value


def _validate_agent_name(name: str) -> str | None:
    """Validate an agent name. Returns error message or None."""
    if len(name) < 2:
        return "Name must be at least 2 characters"
    if not re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$", name):
        return "Must be lowercase alphanumeric with hyphens (e.g., 'my-agent')"
    return None


def _validate_email(email: str) -> str | None:
    """Basic email validation. Returns error message or None."""
    if "@" not in email or "." not in email.split("@")[-1]:
        return "Please enter a valid email address"
    return None


# ─── Main command ────────────────────────────────────────────────────


def init(
    output_dir: str = typer.Argument(
        None,
        help="Directory to create the project in (defaults to agent name)",
    ),
    json_output: bool = typer.Option(
        False,
        "--json",
        help="Output as JSON (for CI/scripting)",
    ),
) -> None:
    """Scaffold a new agent project with an interactive wizard.

    Creates a complete, deployable agent project with:
      - agent.yaml (configuration)
      - agent.py (working example code)
      - requirements.txt (dependencies)
      - .env.example (environment template)
      - README.md (getting started guide)
    """
    if not json_output:
        console.print()
        console.print(
            Panel(
                "[bold]New Agent Project[/bold]\n"
                "[dim]Answer a few questions and you'll have a deployable agent in seconds.[/dim]",
                title="[bold]AgentBreeder[/bold]",
                border_style="blue",
                padding=(1, 2),
            )
        )

    # ── Step 1: Framework ────────────────────────────────────────
    framework = _prompt_selection("What framework?", FRAMEWORKS)

    # ── Step 2: Cloud ────────────────────────────────────────────
    cloud = _prompt_selection("Where will it run?", CLOUDS)

    # ── Step 3: Details ──────────────────────────────────────────
    console.print("\n  [bold]Project details[/bold]\n")

    cwd_name = Path.cwd().name
    default_name = re.sub(r"[^a-z0-9-]", "-", cwd_name.lower()).strip("-") or "my-agent"
    if len(default_name) < 2:
        default_name = "my-agent"

    name = _prompt_text("Agent name", default=default_name, validate_fn=_validate_agent_name)
    team = _prompt_text("Team", default="engineering")

    # Try to get a sensible email default from git config
    git_email = ""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "config", "user.email"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            git_email = result.stdout.strip()
    except Exception:
        pass

    owner = _prompt_text("Owner email", default=git_email, validate_fn=_validate_email)

    # ── Step 4: Generate files ───────────────────────────────────
    project_dir = Path(output_dir) if output_dir else Path.cwd() / name
    project_dir = project_dir.resolve()

    if project_dir.exists() and any(project_dir.iterdir()):
        console.print(
            f"\n  [yellow]Warning:[/yellow] Directory [bold]{project_dir}[/bold] is not empty."
        )
        overwrite = console.input("  [bold]Continue anyway? (y/N): [/bold]").strip().lower()
        if overwrite != "y":
            console.print("  [dim]Aborted.[/dim]")
            raise typer.Exit(code=0)

    project_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "agent.yaml": _agent_yaml(
            name=name,
            framework=framework["key"],
            cloud=cloud["key"],
            model=framework["model"],
            team=team,
            owner=owner,
        ),
        "agent.py": AGENT_PY_GENERATORS[framework["key"]](name),
        "requirements.txt": _requirements(framework["key"]),
        ".env.example": _env_example(framework["key"]),
        "README.md": _readme(name, framework["key"], cloud["key"]),
    }

    if not json_output:
        console.print()
        console.print(Rule(style="dim"))
        console.print()

    created_files = []
    for filename, content in files.items():
        filepath = project_dir / filename
        filepath.write_text(content)
        created_files.append(str(filepath))
        if not json_output:
            console.print(f"  [green]✓[/green] {filename}")

    # ── Step 5: Validate ─────────────────────────────────────────
    yaml_path = project_dir / "agent.yaml"
    validation = validate_config(yaml_path)

    if json_output:
        import json
        import sys

        output = {
            "project_dir": str(project_dir),
            "name": name,
            "framework": framework["key"],
            "cloud": cloud["key"],
            "team": team,
            "owner": owner,
            "files": created_files,
            "valid": validation.valid,
        }
        if not validation.valid:
            output["validation_errors"] = [e.model_dump() for e in validation.errors]
        sys.stdout.write(json.dumps(output, indent=2) + "\n")
        return

    console.print()

    if validation.valid:
        console.print("  [green]✓[/green] agent.yaml validated")
    else:
        console.print("  [yellow]⚠[/yellow] agent.yaml has validation warnings:")
        for err in validation.errors:
            console.print(f"    [dim]- {err.path}: {err.message}[/dim]")

    # ── Step 6: Next steps ───────────────────────────────────────
    rel_dir = os.path.relpath(project_dir, Path.cwd())
    # Use relative path if simple (no ..), otherwise use absolute
    if rel_dir == ".":
        cd_cmd = ""
    elif rel_dir.startswith(".."):
        cd_cmd = f"cd {project_dir}\n  "
    else:
        cd_cmd = f"cd {rel_dir}\n  "

    console.print()
    console.print(
        Panel(
            f"[bold green]Project created![/bold green] {framework['icon']} {name}\n\n"
            f"  [bold]Next steps:[/bold]\n\n"
            f"  [dim]$[/dim] {cd_cmd}pip install -r requirements.txt\n"
            f"  [dim]$[/dim] cp .env.example .env\n"
            f"  [dim]$[/dim] [dim]# Add your API keys to .env[/dim]\n"
            f"  [dim]$[/dim] python agent.py\n"
            f"  [dim]$[/dim] agentbreeder validate agent.yaml\n"
            f"  [dim]$[/dim] agentbreeder deploy agent.yaml --target {cloud['key']}",
            title="Ready",
            border_style="green",
            padding=(1, 2),
        )
    )
    console.print()
