"""agentbreeder ui — start the full dashboard platform locally.

No repo clone required. Pulls pre-built Docker Hub images and starts
postgres + redis + API + dashboard in one command.

Usage:
    agentbreeder ui                 # start in background
    agentbreeder ui --follow        # start and tail logs (Ctrl+C to stop)
    agentbreeder ui --pull          # force image pull before start
"""

from __future__ import annotations

import shutil
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

import typer
from rich.console import Console

console = Console()

# The standalone compose file embedded directly — always version-matched with this CLI.
# Mirrors deploy/docker-compose.standalone.yml; update both on each release.
_COMPOSE_YAML = """\
# AgentBreeder standalone stack — generated by `agentbreeder ui`
# Do not edit this file directly; it is managed by the CLI.

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: agentbreeder
      POSTGRES_USER: agentbreeder
      POSTGRES_PASSWORD: agentbreeder
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agentbreeder -d agentbreeder"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: rajits/agentbreeder-api:latest
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: postgresql+asyncpg://agentbreeder:agentbreeder@postgres:5432/agentbreeder
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    image: rajits/agentbreeder-api:latest
    ports:
      - "{api_port}:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://agentbreeder:agentbreeder@postgres:5432/agentbreeder
      REDIS_URL: redis://redis:6379
      GARDEN_ENV: development
      SECRET_KEY: change-me-in-production
      JWT_SECRET_KEY: change-me-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  dashboard:
    image: rajits/agentbreeder-dashboard:latest
    ports:
      - "{dashboard_port}:3001"
    depends_on:
      api:
        condition: service_healthy

volumes:
  pgdata:
"""

_COMPOSE_PROJECT = "agentbreeder-ui"
_AGENTBREEDER_DIR = Path.home() / ".agentbreeder"
_COMPOSE_PATH = _AGENTBREEDER_DIR / "docker-compose.ui.yml"


def _check_docker() -> None:
    """Raise SystemExit with a helpful message if Docker is not available."""
    if not shutil.which("docker"):
        console.print(
            "\n[bold red]Docker not found.[/bold red]\n\n"
            "  Install Docker Desktop: https://docs.docker.com/get-docker/\n"
        )
        raise typer.Exit(code=1)

    result = subprocess.run(
        ["docker", "info"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        console.print(
            "\n[bold red]Docker daemon is not running.[/bold red]\n\n"
            "  Start Docker Desktop and try again.\n"
        )
        raise typer.Exit(code=1)


def _check_docker_compose() -> None:
    """Raise SystemExit if docker compose v2 is not available."""
    result = subprocess.run(
        ["docker", "compose", "version"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        console.print(
            "\n[bold red]Docker Compose v2 not found.[/bold red]\n\n"
            "  Update Docker Desktop to a recent version which includes Compose v2.\n"
            "  https://docs.docker.com/compose/install/\n"
        )
        raise typer.Exit(code=1)


def _write_compose_file(api_port: int, dashboard_port: int) -> Path:
    """Write the embedded compose YAML to ~/.agentbreeder/docker-compose.ui.yml."""
    _AGENTBREEDER_DIR.mkdir(parents=True, exist_ok=True)
    content = _COMPOSE_YAML.format(api_port=api_port, dashboard_port=dashboard_port)
    _COMPOSE_PATH.write_text(content)
    return _COMPOSE_PATH


def _compose_cmd(compose_path: Path) -> list[str]:
    return ["docker", "compose", "-f", str(compose_path), "-p", _COMPOSE_PROJECT]


def _pull_images(compose_path: Path) -> None:
    console.print("  [dim]Pulling images...[/dim]", end="")
    result = subprocess.run(  # noqa: S603
        [*_compose_cmd(compose_path), "pull"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        console.print(" [yellow]⚠ pull failed, will use cached images[/yellow]")
    else:
        console.print(" [green]✅[/green]")


def _start_stack(compose_path: Path) -> bool:
    result = subprocess.run(  # noqa: S603
        [*_compose_cmd(compose_path), "up", "-d"],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def _poll_health(api_port: int, timeout: int = 90) -> bool:
    """Poll /health until it returns 200 or timeout expires. Returns True on success."""
    url = f"http://localhost:{api_port}/health"
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as resp:  # noqa: S310
                if resp.status == 200:
                    return True
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(3)
    return False


def _stop_stack(compose_path: Path) -> None:
    subprocess.run(  # noqa: S603
        [*_compose_cmd(compose_path), "down"],
        capture_output=True,
    )


def _tail_logs(compose_path: Path) -> None:
    """Tail compose logs until KeyboardInterrupt, then stop the stack."""
    try:
        subprocess.run([*_compose_cmd(compose_path), "logs", "-f"])  # noqa: S603
    except KeyboardInterrupt:
        console.print("\n\n[dim]Stopping AgentBreeder platform...[/dim]")
        _stop_stack(compose_path)
        console.print("[green]Stopped.[/green]\n")


def ui(
    follow: bool = typer.Option(
        False,
        "--follow",
        "-f",
        help="Tail logs after start. Press Ctrl+C to stop the stack.",
    ),
    pull: bool = typer.Option(
        True,
        "--pull/--no-pull",
        help="Pull latest images before starting.",
    ),
    api_port: int = typer.Option(8000, "--api-port", help="Local port for the API server."),
    dashboard_port: int = typer.Option(3001, "--port", help="Local port for the dashboard."),
) -> None:
    """Start the AgentBreeder platform locally (dashboard + API + database).

    No repo clone required — pulls pre-built images from Docker Hub.

    Examples:
        agentbreeder ui                  # start in background
        agentbreeder ui --follow         # start and tail logs
        agentbreeder ui --port 4000      # use a different dashboard port
    """
    console.print()
    console.print("  [bold]AgentBreeder Platform[/bold]")
    console.print("  " + "─" * 35)

    # 1. Preflight checks
    console.print("  [dim]Checking Docker...[/dim]", end="")
    _check_docker()
    _check_docker_compose()
    console.print(" [green]✅[/green]")

    # 2. Write compose file
    compose_path = _write_compose_file(api_port, dashboard_port)

    # 3. Pull images
    if pull:
        _pull_images(compose_path)

    # 4. Start stack
    console.print("  [dim]Starting services...[/dim]", end="")
    if not _start_stack(compose_path):
        console.print(" [red]❌[/red]")
        console.print("\n  [red]Failed to start services.[/red]")
        console.print(f"  Check logs: [dim]docker compose -f {compose_path} logs[/dim]\n")
        raise typer.Exit(code=1)
    console.print(" [green]✅[/green]")

    # 5. Health poll
    console.print("  [dim]Waiting for API health...[/dim]", end="")
    if not _poll_health(api_port):
        console.print(" [red]❌[/red]")
        console.print(
            "\n  [red]API did not become healthy within 90s.[/red]\n"
            f"  Check logs: [dim]docker compose -f {compose_path}"
            f" -p {_COMPOSE_PROJECT} logs api[/dim]\n"
        )
        raise typer.Exit(code=1)
    console.print(" [green]✅[/green]")

    # 6. Success banner
    console.print()
    console.print(f"  Dashboard  →  [bold cyan]http://localhost:{dashboard_port}[/bold cyan]")
    console.print(f"  API        →  [bold cyan]http://localhost:{api_port}[/bold cyan]")
    console.print(f"  API Docs   →  [bold cyan]http://localhost:{api_port}/docs[/bold cyan]")
    console.print()

    if follow:
        console.print("  [dim]Tailing logs (Ctrl+C to stop the stack)...[/dim]\n")
        _tail_logs(compose_path)
    else:
        console.print("  [dim]Stack is running in the background.[/dim]")
        console.print(
            "  [dim]Run [/dim][cyan]agentbreeder ui --follow[/cyan][dim] to tail logs.[/dim]"
        )
        console.print(
            f"  [dim]Run [/dim][cyan]docker compose -f {compose_path} -p {_COMPOSE_PROJECT} down"
            "[/cyan][dim] to stop.[/dim]"
        )
        console.print()
