"""Google Agent Development Kit (ADK) runtime builder.

Validates Google ADK agent code, generates a Dockerfile, and prepares
the build context for containerized deployment.

Supports both agent.py (code-first) and root_agent.yaml (config-first, from
`adk create --type=config`) agent formats.
"""

from __future__ import annotations

import json
import logging
import shutil
import tempfile
from pathlib import Path

from engine.config_parser import AgentConfig
from engine.runtimes.base import (
    ContainerImage,
    RuntimeBuilder,
    RuntimeValidationResult,
    build_env_block,
)

logger = logging.getLogger(__name__)

GOOGLE_ADK_SERVER_TEMPLATE = Path(__file__).parent / "templates" / "google_adk_server.py"

# server_loader.py is generated inline (not a file template) to keep things self-contained.
SERVER_LOADER_CONTENT = '''\
"""server_loader.py — generated by AgentBreeder.

Loads a Google ADK agent from root_agent.yaml using ADK\'s YAML parser.
Imported by server.py when agent.py is not present.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def load_agent_from_yaml(yaml_path: str) -> Any:
    """Parse root_agent.yaml and return the root agent instance."""
    from google.adk.agents import Agent  # noqa: F401 — ensures ADK is importable

    # ADK 1.x exposes agent_from_yaml (or similar) in google.adk.utils.yaml_utils.
    # Try the canonical path; fall back to manual construction if API changes.
    try:
        from google.adk.utils.yaml_utils import agent_from_yaml
        return agent_from_yaml(Path(yaml_path).read_text())
    except ImportError:
        pass

    # Fallback: manual YAML parse into Agent kwargs
    import yaml  # PyYAML is a transitive dep of google-adk
    with open(yaml_path) as f:
        data = yaml.safe_load(f)

    return Agent(
        name=data.get("name", "yaml-agent"),
        model=data.get("model", "gemini-2.0-flash"),
        description=data.get("description", ""),
        instruction=data.get("instruction", ""),
    )
'''

DOCKERFILE_TEMPLATE = """\
FROM python:3.11-slim

WORKDIR /app

# Install dependencies first (layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy agent code
COPY . .

# Google ADK uses Application Default Credentials (ADC).
# To authenticate, mount your service account key and set this env var:
#   ENV GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
# Or use Workload Identity when running on GCP (no key file needed).

# Agent configuration
{env_block}

# AgentBreeder ADK framework config (injected at build time)
{adk_env_block}

# Non-root user for security
RUN useradd -m -r agent && chown -R agent:agent /app
USER agent

EXPOSE 8080

HEALTHCHECK --interval=10s --timeout=5s --retries=3 \\
    CMD python -c "import httpx; httpx.get('http://localhost:8080/health').raise_for_status()"

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]
"""


def _build_adk_env_block(config: AgentConfig) -> str:
    """Generate ENV directive for AGENTBREEDER_ADK_CONFIG from google_adk config."""
    if config.google_adk is None:
        return "# No google_adk config block — using defaults"
    # Exclude session_db_url — it may contain credentials and must not be baked into
    # the image layer. The server template falls back to os.getenv("DATABASE_URL") at
    # runtime, which should be supplied via deploy.secrets or a runtime secret reference.
    adk_dict = config.google_adk.model_dump(exclude_none=True, exclude={"session_db_url"})
    json_val = json.dumps(adk_dict).replace('"', '\\"')
    return f'ENV AGENTBREEDER_ADK_CONFIG="{json_val}"'


class GoogleADKRuntime(RuntimeBuilder):
    """Runtime builder for Google Agent Development Kit (ADK) agents."""

    def validate(self, agent_dir: Path, config: AgentConfig) -> RuntimeValidationResult:
        errors: list[str] = []

        agent_file = agent_dir / "agent.py"
        yaml_file = agent_dir / "root_agent.yaml"

        if not agent_file.exists() and not yaml_file.exists():
            errors.append(
                f"Missing agent.py or root_agent.yaml in {agent_dir}. "
                "Provide agent.py exporting a 'root_agent', 'agent', or 'app' variable, "
                "or a root_agent.yaml produced by `adk create --type=config`."
            )

        # Check for requirements
        has_requirements = (agent_dir / "requirements.txt").exists()
        has_pyproject = (agent_dir / "pyproject.toml").exists()
        if not has_requirements and not has_pyproject:
            errors.append(
                "Missing requirements.txt or pyproject.toml. "
                "Add one with your agent's dependencies (must include google-adk)."
            )

        # Warn if GOOGLE_CLOUD_PROJECT is not referenced in agent.py (non-fatal)
        if agent_file.exists():
            agent_source = agent_file.read_text()
            if "GOOGLE_CLOUD_PROJECT" not in agent_source:
                logger.warning(
                    "agent.py does not reference GOOGLE_CLOUD_PROJECT. "
                    "Set this environment variable for Google Cloud API access. "
                    "The server will fall back to 'agentbreeder-local' if unset."
                )

        # Note: cross-field constraints (session_db_url required for database backend,
        # gcs_bucket required for gcs artifact service) are enforced by Pydantic's
        # GoogleADKConfig model_validator — no need to duplicate them here.

        return RuntimeValidationResult(valid=len(errors) == 0, errors=errors)

    def build(self, agent_dir: Path, config: AgentConfig) -> ContainerImage:
        """Generate Dockerfile and prepare build context."""
        build_dir = Path(tempfile.mkdtemp(prefix="agentbreeder-build-"))

        # Copy agent source code
        for item in agent_dir.iterdir():
            if item.name.startswith(".") or item.name == "__pycache__":
                continue
            dest = build_dir / item.name
            if item.is_dir():
                shutil.copytree(item, dest, ignore=shutil.ignore_patterns("__pycache__", ".git"))
            else:
                shutil.copy2(item, dest)

        # If root_agent.yaml exists, generate server_loader.py in the build context
        if (agent_dir / "root_agent.yaml").exists():
            (build_dir / "server_loader.py").write_text(SERVER_LOADER_CONTENT)
            logger.info("Generated server_loader.py for root_agent.yaml agent")

        # Ensure requirements.txt exists with framework deps
        requirements_file = build_dir / "requirements.txt"
        existing_requirements = ""
        if requirements_file.exists():
            existing_requirements = requirements_file.read_text()

        framework_deps = self.get_requirements(config)
        all_deps = set(existing_requirements.strip().splitlines()) | set(framework_deps)
        requirements_file.write_text("\n".join(sorted(all_deps)) + "\n")

        # Copy the server wrapper template
        if GOOGLE_ADK_SERVER_TEMPLATE.exists():
            shutil.copy2(GOOGLE_ADK_SERVER_TEMPLATE, build_dir / "server.py")

        # Build Dockerfile
        env_block = build_env_block(config, "google_adk")
        adk_env_block = _build_adk_env_block(config)
        dockerfile_content = DOCKERFILE_TEMPLATE.format(
            env_block=env_block,
            adk_env_block=adk_env_block,
        )

        dockerfile = build_dir / "Dockerfile"
        dockerfile.write_text(dockerfile_content)

        tag = f"agentbreeder/{config.name}:{config.version}"

        return ContainerImage(
            tag=tag,
            dockerfile_content=dockerfile_content,
            context_dir=build_dir,
        )

    def get_entrypoint(self, config: AgentConfig) -> str:
        return "uvicorn server:app --host 0.0.0.0 --port 8080"

    def get_requirements(self, config: AgentConfig) -> list[str]:
        deps = [
            "google-adk>=1.29.0",
            "google-generativeai>=0.8.0",
            "fastapi>=0.110.0",
            "uvicorn[standard]>=0.27.0",
            "httpx>=0.27.0",
            "pydantic>=2.0.0",
        ]
        # Add GCS dep when artifact_service=gcs
        if config.google_adk and config.google_adk.artifact_service.value == "gcs":
            deps.append("google-cloud-storage>=2.0.0")
        return deps
